/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedIdiotsRouteRouteImport } from './routes/_authenticated/idiots/route'
import { Route as AuthenticatedIdiotsIndexRouteImport } from './routes/_authenticated/idiots/index'
import { Route as AuthenticatedEventsIndexRouteImport } from './routes/_authenticated/events/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedEventsEditEventIdRouteImport } from './routes/_authenticated/events/edit.$eventId'

const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdiotsRouteRoute =
  AuthenticatedIdiotsRouteRouteImport.update({
    id: '/idiots',
    path: '/idiots',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedIdiotsIndexRoute =
  AuthenticatedIdiotsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedIdiotsRouteRoute,
  } as any)
const AuthenticatedEventsIndexRoute =
  AuthenticatedEventsIndexRouteImport.update({
    id: '/events/',
    path: '/events/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEventsEditEventIdRoute =
  AuthenticatedEventsEditEventIdRouteImport.update({
    id: '/events/edit/$eventId',
    path: '/events/edit/$eventId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/idiots': typeof AuthenticatedIdiotsRouteRouteWithChildren
  '/profile': typeof AuthenticatedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events/': typeof AuthenticatedEventsIndexRoute
  '/idiots/': typeof AuthenticatedIdiotsIndexRoute
  '/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/events': typeof AuthenticatedEventsIndexRoute
  '/idiots': typeof AuthenticatedIdiotsIndexRoute
  '/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/_authenticated/idiots': typeof AuthenticatedIdiotsRouteRouteWithChildren
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/events/': typeof AuthenticatedEventsIndexRoute
  '/_authenticated/idiots/': typeof AuthenticatedIdiotsIndexRoute
  '/_authenticated/events/edit/$eventId': typeof AuthenticatedEventsEditEventIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/idiots'
    | '/profile'
    | '/api/auth/$'
    | '/events/'
    | '/idiots/'
    | '/events/edit/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/profile'
    | '/api/auth/$'
    | '/events'
    | '/idiots'
    | '/events/edit/$eventId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/sign-in'
    | '/sign-up'
    | '/_authenticated/idiots'
    | '/_authenticated/profile'
    | '/api/auth/$'
    | '/_authenticated/events/'
    | '/_authenticated/idiots/'
    | '/_authenticated/events/edit/$eventId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idiots': {
      id: '/_authenticated/idiots'
      path: '/idiots'
      fullPath: '/idiots'
      preLoaderRoute: typeof AuthenticatedIdiotsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/idiots/': {
      id: '/_authenticated/idiots/'
      path: '/'
      fullPath: '/idiots/'
      preLoaderRoute: typeof AuthenticatedIdiotsIndexRouteImport
      parentRoute: typeof AuthenticatedIdiotsRouteRoute
    }
    '/_authenticated/events/': {
      id: '/_authenticated/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof AuthenticatedEventsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/events/edit/$eventId': {
      id: '/_authenticated/events/edit/$eventId'
      path: '/events/edit/$eventId'
      fullPath: '/events/edit/$eventId'
      preLoaderRoute: typeof AuthenticatedEventsEditEventIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedIdiotsRouteRouteChildren {
  AuthenticatedIdiotsIndexRoute: typeof AuthenticatedIdiotsIndexRoute
}

const AuthenticatedIdiotsRouteRouteChildren: AuthenticatedIdiotsRouteRouteChildren =
  {
    AuthenticatedIdiotsIndexRoute: AuthenticatedIdiotsIndexRoute,
  }

const AuthenticatedIdiotsRouteRouteWithChildren =
  AuthenticatedIdiotsRouteRoute._addFileChildren(
    AuthenticatedIdiotsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIdiotsRouteRoute: typeof AuthenticatedIdiotsRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedEventsIndexRoute: typeof AuthenticatedEventsIndexRoute
  AuthenticatedEventsEditEventIdRoute: typeof AuthenticatedEventsEditEventIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIdiotsRouteRoute: AuthenticatedIdiotsRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedEventsIndexRoute: AuthenticatedEventsIndexRoute,
  AuthenticatedEventsEditEventIdRoute: AuthenticatedEventsEditEventIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
